name: egg_sorting_dashboard
description: "A Flutter project for Dashboard Monitoring of Eggs."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: 24.2.9
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  fl_chart: ^0.65.0
  intl: 0.18.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  camera: ^0.10.0+1
  path_provider: ^2.0.14
  path: ^1.8.2
  animations: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/icons/images/logo.png
    - assets/icons/images/banner.png
    - assets/icons/images/transparent-logo.png
    - assets/icons/images/no-bg-icon.png
    - assets/icons/project_image.png
    - assets/icons/client-image.jpg

  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#FFF8E7"
  image: assets/icons/icon.png
  fullscreen: true
  android: true
  ios: true
  android_gravity: center
  android_screen_density: xxxhdpi
  image_dark: assets/icons/icon.png
  android_gravity_dark: center
