// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_dJtsxScA4gLisYkpCWf2p65zOxGodY',
    appId: '1:988449803589:web:749459f185cd61f279c22c',
    messagingSenderId: '988449803589',
    projectId: 'nancyfresheggs',
    authDomain: 'nancyfresheggs.firebaseapp.com',
    storageBucket: 'nancyfresheggs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhD5M90avDvT0sQxPJfHsqZ5QGTg5WPsw',
    appId: '1:988449803589:android:7c7cb42d65c8853f79c22c',
    messagingSenderId: '988449803589',
    projectId: 'nancyfresheggs',
    storageBucket: 'nancyfresheggs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImE17mWvNgmcI1vU0_0ZuNhqP4SYhrRo',
    appId: '1:988449803589:ios:1fff2041696db8a679c22c',
    messagingSenderId: '988449803589',
    projectId: 'nancyfresheggs',
    storageBucket: 'nancyfresheggs.firebasestorage.app',
    iosBundleId: 'com.example.eggSortingDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDImE17mWvNgmcI1vU0_0ZuNhqP4SYhrRo',
    appId: '1:988449803589:ios:1fff2041696db8a679c22c',
    messagingSenderId: '988449803589',
    projectId: 'nancyfresheggs',
    storageBucket: 'nancyfresheggs.firebasestorage.app',
    iosBundleId: 'com.example.eggSortingDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_dJtsxScA4gLisYkpCWf2p65zOxGodY',
    appId: '1:988449803589:web:b4e6d07adb6f680279c22c',
    messagingSenderId: '988449803589',
    projectId: 'nancyfresheggs',
    authDomain: 'nancyfresheggs.firebaseapp.com',
    storageBucket: 'nancyfresheggs.firebasestorage.app',
  );
}
